require 'eventmachine'
require 'google_weather'
require 'active_support/all'
require 'xmpp4r'
require 'xmpp4r/muc'

require 'hipbot/adapters/hipchat'
require 'hipbot/adapters/telnet'
require 'hipbot/bot'
require 'hipbot/configuration'
require 'hipbot/message'
require 'hipbot/reaction'
require 'hipbot/response'
